# Generated by Django 4.2.16 on 2025-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_forget'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_webservice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='webservice_from_who',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=3),
        ),
    ]
