# Generated by Django 4.2.16 on 2025-02-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_webservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webservice_origin',
            field=models.CharField(default='www', max_length=255),
        ),
    ]
