# Generated by Django 4.2.16 on 2025-02-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_webservice_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webservice_campaign_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='webservice_discount_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
