# Generated by Django 4.2.16 on 2025-02-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_webservice_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='webservice_campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='webservice_discount_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
