# Generated by Django 4.2.16 on 2025-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_webservice_campaign_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webservice_total_request_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='webservice_user_request_limit',
            field=models.IntegerField(default=30),
        ),
    ]
