# Generated by Django 4.2.16 on 2025-02-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_webservice_total_request_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webservice_question_price',
            field=models.IntegerField(default=30000),
        ),
    ]
