# Generated by Django 4.2.16 on 2025-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_created_at_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_counter',
            field=models.IntegerField(default=0),
        ),
    ]
