# Generated by Django 4.2.16 on 2025-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_phone_number', models.CharField(max_length=11, unique=True)),
                ('user_full_name', models.CharField(max_length=255)),
                ('orginal_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ref_id', models.CharField(max_length=255)),
                ('discount_code', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_credit', models.IntegerField()),
                ('secondary_credit', models.IntegerField()),
                ('user_os', models.CharField(max_length=255)),
            ],
        ),
    ]
