# Generated by Django 4.2.16 on 2025-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(default='NOK', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user_phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
