# Generated by Django 4.2.16 on 2025-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_transactionhistory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(default='None', max_length=255)),
                ('user_phone_number', models.CharField(max_length=11)),
                ('user_full_name', models.CharField(max_length=255)),
                ('question', models.CharField(default='', max_length=255)),
                ('from_who', models.CharField(default='', max_length=255)),
                ('api_key_name', models.CharField(default='', max_length=255)),
                ('credit', models.IntegerField()),
                ('user_os', models.CharField(max_length=255)),
            ],
        ),
    ]
