# Generated by Django 4.2.16 on 2025-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_questionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
