# Generated by Django 4.2.16 on 2025-02-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_questionhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='webservice_user',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
