# Generated by Django 4.2.16 on 2025-02-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_questionhistory_webservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='webservice_campaign_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='webservice_discount_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
